### ISSUE TITLE
Creating multiple Pdfs in one thread hangs on saveAs

### ISSUE THREAD

**Issue by Req** [mikehaertl/phpwkhtmltopdf#332]
I am creating two ~6Mb Pdfs in the same Laravel Job and the process hangs when saving, First time this runs, it goes to completion. Second time, it hangs after printing "Saving PDF to disk at...". When I inspect the path, I can't see the generated PDF in /tmp -- but if there is only one PDF generated it does work and I can open the generated PDF (it's sent in a zip via email).

Am I doing something wrong? The HTML is kinda complicated, it has 15 images and 15 Google Maps instances rendered.

```
$pdf = new Pdf();
$pdf->setOptions([
	'no-outline',
	'enable-javascript',
	'no-stop-slow-scripts',
	'javascript-delay' => '20000',
	'header-spacing' => '0',
	'footer-spacing' => '-35',
	'margin-top' => '20',
	'margin-left' => '0',
	'margin-right' => '0',
	'margin-bottom' => '20',
	'footer-html' => '<html><body><div style="background-color:#FFF;height:500px;"></div></body></html>',
	'commandOptions' => [
		'useExec' => true,
		'procEnv' => ['LANG' => 'en_US.utf-8'],
	],
]);

$pdf->addPage($html);
$err = $pdf->getError();

if ($err) { Log::warning($err); }

$file = tmpfile();
$path = stream_get_meta_data($file)['uri'] . '.pdf';
Log::debug('Saving PDF to disk at ' . $path);

if (!$pdf->saveAs($path)) {
	Log::debug('Error saving - ' . $pdf->getError());
	throw new Exception('Error Saving PDF: '.$pdf->getError());
}

Log::debug('Save complete!');
```

**Comment by mikehaertl** [comment]
It should be fine. But I wonder why you set `useExec`. Are you on a Windows system? If not, the standard executor should be much safer. I've updated the underlying [php-shellcommand](https://github.com/mikehaertl/php-shellcommand) some weeks ago and it should be much more stable especially with long running processes (see [here](https://github.com/mikehaertl/php-shellcommand/issues/20) for details). Did you try it?

**Comment by Req** [comment]
Hmm, this and my local system are both Linuxes. As for the useExec, I have a comment on it that says `'useExec' => true, // Can help if generation fails without a useful error message`

I don't remember why I wrote that though, it was a long time ago. I'll try removing it! 

I actually tried now and I do see the first generated PDF on disk, I must have looked in the wrong directory or inside a docker or something last time. Strangely, there is a 0-length files created just after that and I don't know where they came from.

```-rw-r--r-- 1 www-data www-data 1.4M Sep 15 09:36 /tmp/phphLEX0w.pdf
-rw------- 1 www-data www-data    0 Sep 15 09:36 /tmp/phpjpS3YJ
-rw-r--r-- 1 www-data www-data 1.4M Sep 15 09:51 /tmp/phpdq1j7b.pdf
-rw------- 1 www-data www-data    0 Sep 15 09:51 /tmp/phpTkXKlz
-rw-r--r-- 1 www-data www-data 1.4M Sep 15 10:17 /tmp/phpabTjDL.pdf
-rw------- 1 www-data www-data    0 Sep 15 10:17 /tmp/phpg3zZ4z
-rw-r--r-- 1 www-data www-data 1.4M Sep 15 10:36 /tmp/php0Mzf02.pdf
-rw------- 1 www-data www-data    0 Sep 15 10:36 /tmp/phpIqE7Jh
```

**Comment by mikehaertl** [comment]
Right, I've updated the README and changed the note. `useExec` should really only be helpful on windows systems.

So did you verify that you use php-shellcommand >= 1.5.0 (installed as dependency)? If not you should update that first.

**Comment by mikehaertl** [comment]
Oh, and just to be save you should also remove that `tmpfile()` and `stream_get_metadata` part. You don't close that filehandle and pass the filename to an already opened file to the pdf library. So it could be blocked or something. Why not use `tmpnam()` instead? That seems to be more what you want anyway.

**Comment by Req** [comment]
I did not try php-shellcommand - I don't understand what that means :smile: 

I didn't know of tempnam() - I tried to use it to generate my path like `$path = tempnam("/tmp", "php-mape-") . ".pdf";` The log shows 
```
[2019-09-15 10:55:59] DEBUG: Saving the PDF to disk at /tmp/php-mape-HujM20.pdf
[2019-09-15 10:56:41] DEBUG: Save complete!
[2019-09-15 10:56:41] DEBUG: Saving the PDF to disk at /tmp/php-mape-5zmlIP.pdf
```

And /tmp looks like 
```
-rw-------  1 www-data www-data    0 Sep 15 10:55 php-mape-HujM20
-rw-r--r--  1 www-data www-data 1.4M Sep 15 10:56 php-mape-HujM20.pdf
-rw-------  1 www-data www-data   81 Sep 15 10:56 tmp_wkhtmlto_pdf_pek6KG.html
-rw-------  1 www-data www-data  19K Sep 15 10:56 tmp_wkhtmlto_pdf_XfBSdg.html
-rw-------  1 www-data www-data    0 Sep 15 10:56 php-mape-5zmlIP
-rw-------  1 www-data www-data 4.7M Sep 15 10:57 tmp_wkhtmlto_pdf_BaVPcp.pdf
```

It still hangs, but that tempfile mess does look really, really suspicious. I haven't done PHP since the 4.x era and I'm kind of lost here. Thank you so much for your assistance - I will try to look at the tempfile generation as it looks super suspicious.

**Comment by mikehaertl** [comment]
> I did not try php-shellcommand ...

It's used by this library so you already have it :smile: . All I'm asking for is to make sure you have the latest version. You can check with `composer info`.

**Comment by Req** [comment]
I was unable to run composer in production, I just don't know how to get it to work. The version is old for sure. Maybe I would have to run a Jenkins build, and I really want to avoid that if I can.

However because the same code using and old version works on my local (dockerized) I don't really think that would be the issue. Again I'm stuck in the originalk situation where saveAs never stops -- neither of the debug messages are ever printed. I have no idea how to get more logs or clues, /var/log/ seems to have nothing :disappointed: 

```
        if (!$pdf->saveAs($path)) {
            Log::debug('Error saving - ' . $pdf->getError());
            throw new Exception('Error Saving PDF: '.$pdf->getError());
        }
        Log::debug('Save complete!');
```
So I tried running the failing command directly 
```
sudo -u www-data wkhtmltopdf --no-outline --enable-javascript 
  --no-stop-slow-scripts --javascript-delay 20000 
  --header-spacing 0 --footer-spacing -35 
  --margin-top 20 --margin-left 0 --margin-right 0 --margin-bottom 20 
  --footer-html /tmp/tmp_wkhtmlto_pdf_MYaZ8n.html 
  /tmp/tmp_wkhtmlto_pdf_iuswBe.html 
  /tmp/tmp_wkhtmlto_pdf_g6Avs9.pdf
Loading pages (1/6)
```
And it worked fine. I don't get it. The wkhtmltopdf process doesn't hang either, it does stop running.

**Comment by mikehaertl** [comment]
Ok, I'm sorry, but I can't help you with that. If you can't get composer to work this should be your main focus. Maybe start with a fresh setup or something.

I don't think, that anything with this library is broken. If you think there's anything to fix, please provide a simple example to reproduce the issue with the latest release.

**Comment by Req** [comment]
I finally managed to update composer and production, now the versions are 
```
mikehaertl/php-shellcommand           1.6.0    An ob...
mikehaertl/php-tmpfile                1.1.1    A con...
mikehaertl/phpwkhtmltopdf             2.4.1    A sli...
```
And it made no difference, it still fails silently when it runs `$pdf->saveAs($path)` the 2nd time.

**Comment by mikehaertl** [comment]
I can only help if I can reproduce the issue. You could start over in a fresh environment and try to rebuild the logic step by step (but with focus on the PDF part!) until it fails. If you can't make it fail, figure out what's the difference between the two setups. If you *can* reproduce the issue, boil the example down to the minimum and paste it here.
